[project]
name = "cloud.colosso"
version = "0.1.0"
description = "Un'app di esempio con OmniPort"  
readme = "README.md"
dependencies = [
    "jinja2",
    "tomli; python_version < '3.11'",
]

[manager.defender]
key = "replace-this-development-key"
soglia_tentativi = 5
timeout_blocchi = 3600
presentation = "demo.dsl"
#persistence = "redis.toml"
#message = "log.toml"

[manager.messenger]
debug_mode = true

#[[message.console]]
#persistence = "log"
#name = "console"

[[message.bus]]
name = "broker"

#[[presentation.console]]
#name = "tui"

[[presentation.starlette]]
name = "web"
host = "127.0.0.1"
port = 8000
cors_origins = []
cors_credentials = false

[[persistence.filesystem]]
name = "log"

[[persistence.filesystem]]
name = "workfolder"

[[persistence.filesystem]]
name = "source"
path = "src/"
watch = true
message = "broker"

[[persistence.api]]
name = "source"
path = "src/"
watch = true
message = "broker"

#[[network.neural]]
#name = "decoder"
#input = 40
#hidden = 2048
#output = 2048