[project]
name = "cloud.colosso"
version = "0.1.0"
description = "Un'app di esempio con OmniPort"  
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "jinja2",
    "tomli",
    "cerberus",
]

[manager.defender]
key = "replace-this-development-key"
soglia_tentativi = 5
timeout_blocchi = 3600

[manager.presenter]
presentation = "presentation.dsl"

[manager.messenger]
debug_mode = true
message = "message.dsl"

[manager.authenticator]
authentication = "authentication.dsl"

[manager.storekeeper]
persistence = "persistence.dsl"

# -----------------------------------------------
# ADAPTERS
# -----------------------------------------------

[[message.bus]]
name = "broker"
implementation = "bus"

[[sensation.text]]
name = "copilot"
implementation = "voice"

#[[network.neural]]
#name = "copilot"
#implementation = "llm"

[[actuation.audio]]
name = "copilot"
implementation = "voice"