[project]
name = "cloud.colosso"
version = "0.1.0"
description = "Un'app di esempio con OmniPort"  
readme = "README.md"
dependencies = [
    "jinja2",
    "tomli; python_version < '3.11'",
]

[manager.defender]
key = "replace-this-development-key"
soglia_tentativi = 5
timeout_blocchi = 3600
presentation = "demo.dsl"
#persistence = "redis.toml"
#message = "log.toml"

[manager.messenger]
debug_mode = true

#[[message.console]]
#persistence = "log"
#name = "console"

[[message.bus]]
name = "broker"

#[[presentation.console]]
#name = "tui"

[[presentation.starlette]]
name = "web"
host = "127.0.0.1"
port = 8000
cors_origins = []
cors_credentials = false

[[persistence.filesystem]]
name = "log"

[[persistence.filesystem]]
name = "workfolder"

[[persistence.filesystem]]
name = "source"
path = "src/"
watch = true
message = "broker"

[[authentication.oauth]]
name = "glpi-oauth"
token_url = '{{ env.get("GLPI_TOKEN_URL", "https://37.99.229.247/api.php/token") }}'
grant_type = '{{ env.get("GLPI_GRANT_TYPE", "password") }}'
client_id = '{{ env["GLPI_CLIENT_ID"] }}'
client_secret = '{{ env["GLPI_CLIENT_SECRET"] }}'
auth_style = '{{ env.get("GLPI_AUTH_STYLE", "body") }}'
username = '{{ env["GLPI_USERNAME"] }}'
password = '{{ env["GLPI_PASSWORD"] }}'
scope = '{{ env.get("GLPI_SCOPE", "api") }}'
verify_ssl = '{{ env.get("GLPI_VERIFY_SSL", "false") }}'

[[persistence.api]]
name = "GLPI"
url = '{{ env.get("GLPI_API_URL", "https://37.99.229.247/") }}'
auth = '{{ env.get("GLPI_AUTH_NAME", "glpi-oauth") }}'
app_token = '{{ env["GLPI_APP_TOKEN"] }}'
timeout = '{{ env.get("GLPI_TIMEOUT", "30") }}'
verify_ssl = '{{ env.get("GLPI_VERIFY_SSL", "false") }}'