# Generated by python -m framework.service.scheme_codegen; do not edit.
from collections.abc import Mapping
from typing import Any
from typing import Literal
from datetime import datetime
from typing import NotRequired, Required, TypedDict, Unpack
from framework.service.scheme import Scheme

class ActuationSchemeKwargs(TypedDict, total=False):
    type: Required[Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]]
    url: Required[str]
    tls: Required[dict[str, Any]]
    authentication: NotRequired[dict[str, Any]]
    authorization: NotRequired[dict[str, Any]]
    data_protection: NotRequired[dict[str, Any]]
    rate_limiting_and_quotas: NotRequired[dict[str, Any]]
    secrets_management: NotRequired[dict[str, Any]]
    audit_logging: NotRequired[dict[str, Any]]
    network_security: NotRequired[dict[str, Any]]
    encryption_at_rest: NotRequired[dict[str, Any]]

class ActuatorSchemeKwargs(TypedDict, total=False):
    operation: NotRequired[Literal["execute_command", "set_state", "set_maintenance_mode", "toggle_feature", "control_data_stream", "run_task"]]
    device_id: NotRequired[str]
    command: NotRequired[str | None]
    payload: NotRequired[dict[str, Any] | None]
    state: NotRequired[dict[str, Any] | None]
    enabled: NotRequired[bool]
    feature_name: NotRequired[str]
    stream_id: NotRequired[str]
    action: NotRequired[Literal["start", "resume", "stop", "pause"]]
    task_name: NotRequired[str]
    parameters: NotRequired[dict[str, Any] | None]

class AdaptersSchemeKwargs(TypedDict, total=False):
    wasm: NotRequired[Any]
    starlette: NotRequired[Any]
    logging: NotRequired[Any]
    websocket: NotRequired[Any]
    api: NotRequired[Any]
    flow: NotRequired[Any]
    mqtt: NotRequired[Any]
    oauth: NotRequired[Any]
    jwt: NotRequired[Any]
    supabase: NotRequired[Any]
    fs: NotRequired[Any]
    flutter: NotRequired[Any]
    ansible: NotRequired[Any]
    log: NotRequired[Any]
    console: NotRequired[Any]
    redis: NotRequired[Any]

class AttributesSchemeKwargs(TypedDict, total=False):
    id: NotRequired[dict[str, Any]]
    name: NotRequired[dict[str, Any]]
    tooltip: NotRequired[dict[str, Any]]
    placeholder: NotRequired[dict[str, Any]]
    value: NotRequired[dict[str, Any]]
    state: NotRequired[dict[str, Any]]
    click: NotRequired[dict[str, Any]]
    change: NotRequired[dict[str, Any]]
    route: NotRequired[dict[str, Any]]
    init: NotRequired[dict[str, Any]]
    action: NotRequired[dict[str, Any]]
    width: NotRequired[dict[str, Any]]
    height: NotRequired[dict[str, Any]]
    space: NotRequired[dict[str, Any]]
    expand: NotRequired[dict[str, Any]]
    collapse: NotRequired[dict[str, Any]]
    border: NotRequired[dict[str, Any]]
    margin: NotRequired[dict[str, Any]]
    padding: NotRequired[dict[str, Any]]
    size: NotRequired[dict[str, Any]]
    position: NotRequired[dict[str, Any]]
    style: NotRequired[dict[str, Any]]
    shadow: NotRequired[dict[str, Any]]
    opacity: NotRequired[dict[str, Any]]

class AuthenticationSchemeKwargs(TypedDict, total=False):
    policy_name: Required[str]
    security: Required[dict[str, Any]]
    allowed_methods: Required[list[Literal["password", "mfa_totp", "mfa_sms", "passkey_webauthn", "sso_saml", "sso_oidc", "magic_link"]]]
    password_policy: NotRequired[dict[str, Any]]
    mfa_policy: Required[dict[str, Any]]
    session_and_token: Required[dict[str, Any]]
    account_lockout: Required[dict[str, Any]]
    sso_federation: NotRequired[dict[str, Any]]

class ContractSchemeKwargs(TypedDict, total=False):
    contract_version: Required[int]
    exports: Required[dict[str, Any]]
    hashes: Required[dict[str, Any]]
    requires: NotRequired[list[str]]

class FileSchemeKwargs(TypedDict, total=False):
    path: NotRequired[str]
    name: Required[str]
    extension: NotRequired[str]
    mime_type: NotRequired[str]
    size: NotRequired[int]
    encoding: NotRequired[Literal["utf-8", "ascii", "latin-1", "utf-16"]]
    content: NotRequired[str | None]
    type: NotRequired[str]
    relative_path: NotRequired[str]
    absolute_path: NotRequired[str]
    metadata: NotRequired[dict[str, Any] | None]
    permissions: NotRequired[str | None]
    owner: NotRequired[str | None]
    created_at: NotRequired[datetime | None]
    modified_at: NotRequired[datetime | None]
    accessed_at: NotRequired[datetime | None]

class MessageSchemeKwargs(TypedDict, total=False):
    type: Required[Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]]
    url: Required[str]
    tls: Required[dict[str, Any]]
    authentication: NotRequired[dict[str, Any]]
    authorization: NotRequired[dict[str, Any]]
    data_protection: NotRequired[dict[str, Any]]
    rate_limiting_and_quotas: NotRequired[dict[str, Any]]
    secrets_management: NotRequired[dict[str, Any]]
    audit_logging: NotRequired[dict[str, Any]]
    network_security: NotRequired[dict[str, Any]]
    encryption_at_rest: NotRequired[dict[str, Any]]

class MessengerSchemeKwargs(TypedDict, total=False):
    message: Required[Any]
    domain: Required[str]
    adapter: NotRequired[str]
    routing: NotRequired[Literal["m2m", "p2p", "multicast", "anycast", "unicast", "broadcast"]]
    sender: NotRequired[str]
    receiver: NotRequired[str]
    timestamp: NotRequired[str]
    identifier: NotRequired[str | None]
    priority: NotRequired[Literal["low", "normal", "high", "critical"]]

class NetworkSchemeKwargs(TypedDict, total=False):
    type: Required[Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]]
    url: Required[str]
    tls: Required[dict[str, Any]]
    authentication: NotRequired[dict[str, Any]]
    authorization: NotRequired[dict[str, Any]]
    data_protection: NotRequired[dict[str, Any]]
    rate_limiting_and_quotas: NotRequired[dict[str, Any]]
    secrets_management: NotRequired[dict[str, Any]]
    audit_logging: NotRequired[dict[str, Any]]
    network_security: NotRequired[dict[str, Any]]
    encryption_at_rest: NotRequired[dict[str, Any]]

class PersistenceSchemeKwargs(TypedDict, total=False):
    storage_type: Required[Literal["filesystem", "s3_object_storage", "relational_db", "nosql_db", "rest_api", "graphql_api"]]
    connection: Required[dict[str, Any]]
    crud_permissions: Required[dict[str, Any]]
    persistence_policy: Required[dict[str, Any]]
    authentication: NotRequired[dict[str, Any]]
    encryption: NotRequired[dict[str, Any]]
    audit_trail: NotRequired[dict[str, Any]]

class PolicySchemeKwargs(TypedDict, total=False):
    effect: NotRequired[Literal["allow", "deny"]]
    target: NotRequired[dict[str, Any]]
    description: NotRequired[str]
    condition: NotRequired[Any]

class PresentationSchemeKwargs(TypedDict, total=False):
    presentation_type: Required[Literal["rest_api", "graphql", "websocket", "grpc", "web_server_html"]]
    cors_policy: Required[dict[str, Any]]
    security_and_waf: Required[dict[str, Any]]
    authentication_guards: Required[dict[str, Any]]
    rate_limiting: NotRequired[dict[str, Any]]
    caching_and_cdn: NotRequired[dict[str, Any]]
    documentation: NotRequired[dict[str, Any]]

class RequirementSchemeKwargs(TypedDict, total=False):
    service: NotRequired[Literal["persistence", "messaging", "authentication", "authorization", "presentation", "network", "logging", "monitoring", "integration", "cache"]]
    interface: NotRequired[str]
    platform: NotRequired[Literal["server", "browser", "mobile", "embedded"]]
    provider: NotRequired[str]
    capabilities: NotRequired[dict[str, Any]]
    constraints: NotRequired[dict[str, Any]]
    sla: NotRequired[UserScheme]
    priority: NotRequired[Literal["low", "normal", "high", "critical"]]
    cost_sensitivity: NotRequired[Literal["low", "medium", "high"]]

class ResultSchemeKwargs(TypedDict, total=False):
    ok: NotRequired[bool]
    data: NotRequired[dict[str, Any] | list[Any] | str | int | float | bool | Any]
    error: NotRequired[dict[str, Any]]

class RoleSchemeKwargs(TypedDict, total=False):
    id: Required[str]
    name: Required[str]
    description: Required[str]
    resources: Required[list[str]]

class RouteSchemeKwargs(TypedDict, total=False):
    path: Required[str]
    method: NotRequired[str]
    type: Required[Literal["view", "authenticate", "terminate", "activate", "reinstate"]]
    view: NotRequired[str]
    controllers: NotRequired[list[str]]

class SensationSchemeKwargs(TypedDict, total=False):
    type: Required[Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]]
    url: Required[str]
    tls: Required[dict[str, Any]]
    authentication: NotRequired[dict[str, Any]]
    authorization: NotRequired[dict[str, Any]]
    data_protection: NotRequired[dict[str, Any]]
    rate_limiting_and_quotas: NotRequired[dict[str, Any]]
    secrets_management: NotRequired[dict[str, Any]]
    audit_logging: NotRequired[dict[str, Any]]
    network_security: NotRequired[dict[str, Any]]
    encryption_at_rest: NotRequired[dict[str, Any]]

class SensorSchemeKwargs(TypedDict, total=False):
    operation: NotRequired[Literal["read", "read_all", "calibrate", "set_threshold"]]
    sensor_id: NotRequired[str]
    field: NotRequired[str | None]
    offset: NotRequired[int | float]
    min_value: NotRequired[int | float | None]
    max_value: NotRequired[int | float | None]
    parameters: NotRequired[dict[str, Any] | None]

class SessionSchemeKwargs(TypedDict, total=False):
    id: NotRequired[str]
    errors: NotRequired[list[Any]]
    providers: NotRequired[dict[str, Any]]
    ip: NotRequired[str]
    current_url: NotRequired[dict[str, Any]]
    previous_url: NotRequired[str]
    user: NotRequired[UserScheme]
    user_agent: NotRequired[str]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]

class SessionDataSchemeKwargs(TypedDict, total=False):
    id: Required[str]
    context: Required[dict[str, Any]]
    authentication: Required[dict[str, Any]]
    results: Required[dict[str, Any]]

class SlaSchemeKwargs(TypedDict, total=False):
    latency_ms: Required[float]
    throughput_mbs: Required[float]
    iops: Required[int]
    error_rate_pct: Required[float]
    availability_pct: Required[float]
    max_concurrent_conn: NotRequired[int]
    storage_total_size: NotRequired[int | float]
    cost_per_unit: NotRequired[float]
    service_tier: NotRequired[Literal["SSD", "HDD", "PREMIUM", "STANDARD", "DEFAULT"]]

class StorekeeperSchemeKwargs(TypedDict, total=False):
    provider: NotRequired[str]
    location: NotRequired[str | None]
    operation: NotRequired[Literal["create", "read", "update", "delete", "view"]]
    repository: Required[str]
    id: NotRequired[str]
    exclude_dirs: NotRequired[list[str]]
    filter: NotRequired[dict[str, Any] | None]
    payload: NotRequired[dict[str, Any] | None]

class TagsSchemeKwargs(TypedDict, total=False):
    Card: NotRequired[dict[str, Any]]
    Data: NotRequired[dict[str, Any]]
    Media: NotRequired[dict[str, Any]]
    Navigation: NotRequired[dict[str, Any]]
    View: NotRequired[dict[str, Any]]
    Messenger: NotRequired[dict[str, Any]]
    Message: NotRequired[dict[str, Any]]
    Defender: NotRequired[dict[str, Any]]
    Column: NotRequired[dict[str, Any]]
    Row: NotRequired[dict[str, Any]]
    Container: NotRequired[dict[str, Any]]
    Storekeeper: NotRequired[dict[str, Any]]
    Input: NotRequired[dict[str, Any]]
    Action: NotRequired[dict[str, Any]]
    Window: NotRequired[dict[str, Any]]
    Text: NotRequired[dict[str, Any]]
    Group: NotRequired[dict[str, Any]]

class TransactionSchemeKwargs(TypedDict, total=False):
    identifier: NotRequired[str]
    success: NotRequired[bool]
    action: NotRequired[str]
    time: NotRequired[str]
    worker: NotRequired[str]
    parameters: NotRequired[dict[str, Any]]
    errors: NotRequired[list[Any]]
    data: NotRequired[Any | None]

class UrlSchemeKwargs(TypedDict, total=False):
    url: Required[str]
    protocol: NotRequired[str]
    host: NotRequired[str]
    port: NotRequired[int]
    path: NotRequired[list[str]]
    query: NotRequired[dict[str, list[str]]]
    fragment: NotRequired[dict[str, list[str]]]

class UserSchemeKwargs(TypedDict, total=False):
    identifier: Required[str]
    username: Required[str]
    role: Required[Literal["admin", "user", "guest"]]
    avatar: Required[str]

class DomainSchemeKwargs(TypedDict, total=False):
    id: Required[str]
    description: NotRequired[str | None]
    status: Required[Literal["pending", "active", "inactive", "suspended"]]
    ssl_enabled: NotRequired[bool]
    dns_records: NotRequired[list[str]]
    server: NotRequired[str | None]
    container: NotRequired[str | None]
    service: NotRequired[str | None]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]
    domain: Required[str]
    owner: NotRequired[str]

class EmailSchemeKwargs(TypedDict, total=False):
    email: Required[str]

class MediaSchemeKwargs(TypedDict, total=False):
    id: Required[int]
    created_at: NotRequired[str]
    url: Required[str]
    type: Required[str]
    tags: NotRequired[dict[str, Any] | None]
    category: NotRequired[str | None]
    title: NotRequired[str | None]
    owner: Required[str]

class PasswordSchemeKwargs(TypedDict, total=False):
    password: Required[str]

class ProductSchemeKwargs(TypedDict, total=False):
    id: NotRequired[str]
    name: Required[str]
    slug: Required[str]
    description: NotRequired[str | None]
    price: Required[int | float]
    category: NotRequired[str | None]
    sku: NotRequired[str | None]
    images: NotRequired[str | None]
    created_at: NotRequired[str]
    updated_at: NotRequired[str | None]

class TaskSchemeKwargs(TypedDict, total=False):
    id: NotRequired[str]
    title: Required[str]
    description: NotRequired[str | None]
    file: NotRequired[str | None]
    status: Required[Literal["backlog", "todo", "in_progress", "review", "done"]]
    assigned_to: NotRequired[str | None]
    started_at: NotRequired[str | None]
    priority: NotRequired[Literal["low", "medium", "high", "critical"]]
    created_at: NotRequired[str]
    updated_at: NotRequired[str | None]
    completed_at: NotRequired[str | None]

class TicketSchemeKwargs(TypedDict, total=False):
    id: NotRequired[int]
    name: NotRequired[str | None]
    content: NotRequired[str | None]
    status: NotRequired[int | None]
    priority: NotRequired[int | None]
    date_creation: NotRequired[str | None]
    date_mod: NotRequired[str | None]
    entity: NotRequired[dict[str, Any] | None]

class UsernameSchemeKwargs(TypedDict, total=False):
    username: Required[str]

class ActuationScheme(Scheme):
    type: Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]
    url: str
    tls: dict[str, Any]
    authentication: dict[str, Any] | None
    authorization: dict[str, Any] | None
    data_protection: dict[str, Any] | None
    rate_limiting_and_quotas: dict[str, Any] | None
    secrets_management: dict[str, Any] | None
    audit_logging: dict[str, Any] | None
    network_security: dict[str, Any] | None
    encryption_at_rest: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[ActuationSchemeKwargs]) -> None: ...

class ActuatorScheme(Scheme):
    operation: Literal["execute_command", "set_state", "set_maintenance_mode", "toggle_feature", "control_data_stream", "run_task"]
    device_id: str | None
    command: str | None
    payload: dict[str, Any] | None
    state: dict[str, Any] | None
    enabled: bool | None
    feature_name: str | None
    stream_id: str | None
    action: Literal["start", "resume", "stop", "pause"] | None
    task_name: str | None
    parameters: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[ActuatorSchemeKwargs]) -> None: ...

class AdaptersScheme(Scheme):
    wasm: Any | None
    starlette: Any | None
    logging: Any | None
    websocket: Any | None
    api: Any | None
    flow: Any | None
    mqtt: Any | None
    oauth: Any | None
    jwt: Any | None
    supabase: Any | None
    fs: Any | None
    flutter: Any | None
    ansible: Any | None
    log: Any | None
    console: Any | None
    redis: Any | None
    def __init__(self, **kwargs: Unpack[AdaptersSchemeKwargs]) -> None: ...

class AttributesScheme(Scheme):
    id: dict[str, Any] | None
    name: dict[str, Any] | None
    tooltip: dict[str, Any] | None
    placeholder: dict[str, Any] | None
    value: dict[str, Any] | None
    state: dict[str, Any] | None
    click: dict[str, Any] | None
    change: dict[str, Any] | None
    route: dict[str, Any] | None
    init: dict[str, Any] | None
    action: dict[str, Any] | None
    width: dict[str, Any] | None
    height: dict[str, Any] | None
    space: dict[str, Any] | None
    expand: dict[str, Any] | None
    collapse: dict[str, Any] | None
    border: dict[str, Any] | None
    margin: dict[str, Any] | None
    padding: dict[str, Any] | None
    size: dict[str, Any] | None
    position: dict[str, Any] | None
    style: dict[str, Any] | None
    shadow: dict[str, Any] | None
    opacity: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[AttributesSchemeKwargs]) -> None: ...

class AuthenticationScheme(Scheme):
    policy_name: str
    security: dict[str, Any]
    allowed_methods: list[Literal["password", "mfa_totp", "mfa_sms", "passkey_webauthn", "sso_saml", "sso_oidc", "magic_link"]]
    password_policy: dict[str, Any] | None
    mfa_policy: dict[str, Any]
    session_and_token: dict[str, Any]
    account_lockout: dict[str, Any]
    sso_federation: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[AuthenticationSchemeKwargs]) -> None: ...

class ContractScheme(Scheme):
    contract_version: int
    exports: dict[str, Any]
    hashes: dict[str, Any]
    requires: list[str]
    def __init__(self, **kwargs: Unpack[ContractSchemeKwargs]) -> None: ...

class FileScheme(Scheme):
    path: str | None
    name: str
    extension: str | None
    mime_type: str
    size: int
    encoding: Literal["utf-8", "ascii", "latin-1", "utf-16"]
    content: str | None
    type: str | None
    relative_path: str | None
    absolute_path: str | None
    metadata: dict[str, Any] | None
    permissions: str | None
    owner: str | None
    created_at: datetime | None
    modified_at: datetime | None
    accessed_at: datetime | None
    def __init__(self, **kwargs: Unpack[FileSchemeKwargs]) -> None: ...

class MessageScheme(Scheme):
    type: Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]
    url: str
    tls: dict[str, Any]
    authentication: dict[str, Any] | None
    authorization: dict[str, Any] | None
    data_protection: dict[str, Any] | None
    rate_limiting_and_quotas: dict[str, Any] | None
    secrets_management: dict[str, Any] | None
    audit_logging: dict[str, Any] | None
    network_security: dict[str, Any] | None
    encryption_at_rest: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[MessageSchemeKwargs]) -> None: ...

class MessengerScheme(Scheme):
    message: Any
    domain: str
    adapter: str | None
    routing: Literal["m2m", "p2p", "multicast", "anycast", "unicast", "broadcast"]
    sender: str
    receiver: str
    timestamp: str
    identifier: str | None
    priority: Literal["low", "normal", "high", "critical"]
    def __init__(self, **kwargs: Unpack[MessengerSchemeKwargs]) -> None: ...

class NetworkScheme(Scheme):
    type: Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]
    url: str
    tls: dict[str, Any]
    authentication: dict[str, Any] | None
    authorization: dict[str, Any] | None
    data_protection: dict[str, Any] | None
    rate_limiting_and_quotas: dict[str, Any] | None
    secrets_management: dict[str, Any] | None
    audit_logging: dict[str, Any] | None
    network_security: dict[str, Any] | None
    encryption_at_rest: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[NetworkSchemeKwargs]) -> None: ...

class PersistenceScheme(Scheme):
    storage_type: Literal["filesystem", "s3_object_storage", "relational_db", "nosql_db", "rest_api", "graphql_api"]
    connection: dict[str, Any]
    crud_permissions: dict[str, Any]
    persistence_policy: dict[str, Any]
    authentication: dict[str, Any] | None
    encryption: dict[str, Any] | None
    audit_trail: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[PersistenceSchemeKwargs]) -> None: ...

class PolicyScheme(Scheme):
    effect: Literal["allow", "deny"]
    target: dict[str, Any]
    description: str
    condition: Any
    def __init__(self, **kwargs: Unpack[PolicySchemeKwargs]) -> None: ...

class PresentationScheme(Scheme):
    presentation_type: Literal["rest_api", "graphql", "websocket", "grpc", "web_server_html"]
    cors_policy: dict[str, Any]
    security_and_waf: dict[str, Any]
    authentication_guards: dict[str, Any]
    rate_limiting: dict[str, Any] | None
    caching_and_cdn: dict[str, Any] | None
    documentation: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[PresentationSchemeKwargs]) -> None: ...

class RequirementScheme(Scheme):
    service: Literal["persistence", "messaging", "authentication", "authorization", "presentation", "network", "logging", "monitoring", "integration", "cache"] | None
    interface: str | None
    platform: Literal["server", "browser", "mobile", "embedded"] | None
    provider: str | None
    capabilities: dict[str, Any] | None
    constraints: dict[str, Any] | None
    sla: UserScheme | None
    priority: Literal["low", "normal", "high", "critical"] | None
    cost_sensitivity: Literal["low", "medium", "high"] | None
    def __init__(self, **kwargs: Unpack[RequirementSchemeKwargs]) -> None: ...

class ResultScheme(Scheme):
    ok: bool
    data: dict[str, Any] | list[Any] | str | int | float | bool | Any
    error: dict[str, Any]
    def __init__(self, **kwargs: Unpack[ResultSchemeKwargs]) -> None: ...

class RoleScheme(Scheme):
    id: str
    name: str
    description: str
    resources: list[str]
    def __init__(self, **kwargs: Unpack[RoleSchemeKwargs]) -> None: ...

class RouteScheme(Scheme):
    path: str
    method: str
    type: Literal["view", "authenticate", "terminate", "activate", "reinstate"]
    view: str
    controllers: list[str]
    def __init__(self, **kwargs: Unpack[RouteSchemeKwargs]) -> None: ...

class SensationScheme(Scheme):
    type: Literal["redis", "rabbitmq", "kafka", "event_bus", "activemq", "sqs"]
    url: str
    tls: dict[str, Any]
    authentication: dict[str, Any] | None
    authorization: dict[str, Any] | None
    data_protection: dict[str, Any] | None
    rate_limiting_and_quotas: dict[str, Any] | None
    secrets_management: dict[str, Any] | None
    audit_logging: dict[str, Any] | None
    network_security: dict[str, Any] | None
    encryption_at_rest: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[SensationSchemeKwargs]) -> None: ...

class SensorScheme(Scheme):
    operation: Literal["read", "read_all", "calibrate", "set_threshold"]
    sensor_id: str | None
    field: str | None
    offset: int | float | None
    min_value: int | float | None
    max_value: int | float | None
    parameters: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[SensorSchemeKwargs]) -> None: ...

class SessionScheme(Scheme):
    id: str
    errors: list[Any]
    providers: dict[str, Any]
    ip: str | None
    current_url: dict[str, Any]
    previous_url: str | None
    user: UserScheme
    user_agent: str | None
    created_at: datetime | None
    updated_at: datetime | None
    def __init__(self, **kwargs: Unpack[SessionSchemeKwargs]) -> None: ...

class SessionDataScheme(Scheme):
    id: str
    context: dict[str, Any]
    authentication: dict[str, Any]
    results: dict[str, Any]
    def __init__(self, **kwargs: Unpack[SessionDataSchemeKwargs]) -> None: ...

class SlaScheme(Scheme):
    latency_ms: float
    throughput_mbs: float
    iops: int
    error_rate_pct: float
    availability_pct: float
    max_concurrent_conn: int | None
    storage_total_size: int | float | None
    cost_per_unit: float | None
    service_tier: Literal["SSD", "HDD", "PREMIUM", "STANDARD", "DEFAULT"] | None
    def __init__(self, **kwargs: Unpack[SlaSchemeKwargs]) -> None: ...

class StorekeeperScheme(Scheme):
    provider: str
    location: str | None
    operation: Literal["create", "read", "update", "delete", "view"]
    repository: str
    id: str | None
    exclude_dirs: list[str] | None
    filter: dict[str, Any] | None
    payload: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[StorekeeperSchemeKwargs]) -> None: ...

class TagsScheme(Scheme):
    Card: dict[str, Any] | None
    Data: dict[str, Any] | None
    Media: dict[str, Any] | None
    Navigation: dict[str, Any] | None
    View: dict[str, Any] | None
    Messenger: dict[str, Any] | None
    Message: dict[str, Any] | None
    Defender: dict[str, Any] | None
    Column: dict[str, Any] | None
    Row: dict[str, Any] | None
    Container: dict[str, Any] | None
    Storekeeper: dict[str, Any] | None
    Input: dict[str, Any] | None
    Action: dict[str, Any] | None
    Window: dict[str, Any] | None
    Text: dict[str, Any] | None
    Group: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[TagsSchemeKwargs]) -> None: ...

class TransactionScheme(Scheme):
    identifier: str
    success: bool
    action: str
    time: str
    worker: str
    parameters: dict[str, Any]
    errors: list[Any]
    data: Any | None
    def __init__(self, **kwargs: Unpack[TransactionSchemeKwargs]) -> None: ...

class UrlScheme(Scheme):
    url: str
    protocol: str | None
    host: str | None
    port: int | None
    path: list[str] | None
    query: dict[str, list[str]] | None
    fragment: dict[str, list[str]] | None
    def __init__(self, **kwargs: Unpack[UrlSchemeKwargs]) -> None: ...

class UserScheme(Scheme):
    identifier: str
    username: str
    role: Literal["admin", "user", "guest"]
    avatar: str
    def __init__(self, **kwargs: Unpack[UserSchemeKwargs]) -> None: ...

class DomainScheme(Scheme):
    id: str
    description: str | None
    status: Literal["pending", "active", "inactive", "suspended"]
    ssl_enabled: bool | None
    dns_records: list[str]
    server: str | None
    container: str | None
    service: str | None
    created_at: str | None
    updated_at: str | None
    domain: str
    owner: str | None
    def __init__(self, **kwargs: Unpack[DomainSchemeKwargs]) -> None: ...

class EmailScheme(Scheme):
    email: str
    def __init__(self, **kwargs: Unpack[EmailSchemeKwargs]) -> None: ...

class MediaScheme(Scheme):
    id: int
    created_at: str | None
    url: str
    type: str
    tags: dict[str, Any] | None
    category: str | None
    title: str | None
    owner: str
    def __init__(self, **kwargs: Unpack[MediaSchemeKwargs]) -> None: ...

class PasswordScheme(Scheme):
    password: str
    def __init__(self, **kwargs: Unpack[PasswordSchemeKwargs]) -> None: ...

class ProductScheme(Scheme):
    id: str | None
    name: str
    slug: str
    description: str | None
    price: int | float
    category: str | None
    sku: str | None
    images: str | None
    created_at: str | None
    updated_at: str | None
    def __init__(self, **kwargs: Unpack[ProductSchemeKwargs]) -> None: ...

class TaskScheme(Scheme):
    id: str | None
    title: str
    description: str | None
    file: str | None
    status: Literal["backlog", "todo", "in_progress", "review", "done"]
    assigned_to: str | None
    started_at: str | None
    priority: Literal["low", "medium", "high", "critical"]
    created_at: str | None
    updated_at: str | None
    completed_at: str | None
    def __init__(self, **kwargs: Unpack[TaskSchemeKwargs]) -> None: ...

class TicketScheme(Scheme):
    id: int | None
    name: str | None
    content: str | None
    status: int | None
    priority: int | None
    date_creation: str | None
    date_mod: str | None
    entity: dict[str, Any] | None
    def __init__(self, **kwargs: Unpack[TicketSchemeKwargs]) -> None: ...

class UsernameScheme(Scheme):
    username: str
    def __init__(self, **kwargs: Unpack[UsernameSchemeKwargs]) -> None: ...

SCHEME_TYPES: dict[str, type[Scheme]]

def bind_schemas(schemas: Mapping[str, Any]) -> None: ...
